title: TRIAL WEBSITE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://AryanilPanja.github.io/trialsite

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/AryanilPanja/trialsite
